# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voorhees < Formula
  desc "Melvin's projects."
  homepage "https://melvin.la"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Nivl/voorhees/releases/download/v0.0.2/voorhees_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "f5d6e1b272225cb52ac3a102055150f40313668c70e81c203f2c43c650a1e13f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Nivl/voorhees/releases/download/v0.0.2/voorhees_0.0.2_Linux_x86_64.tar.gz"
    sha256 "61770729c963532f66da5358021d76c5079bbc3a8ae5cd580542c57651681af7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Nivl/voorhees/releases/download/v0.0.2/voorhees_0.0.2_Linux_arm64.tar.gz"
    sha256 "4e7e6271349ae59950934f2acfd2590558980046dc5b9712b2eddd87c0dc15ba"
  end

  def install
    bin.install "voorhees"
  end

  test do
    system "#{bin}/voorhees --version"
  end
end
