# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voorhees < Formula
  desc "Melvin's projects."
  homepage "https://melvin.la"
  version "0.9.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Nivl/voorhees/releases/download/v0.9.0/voorhees_0.9.0_Darwin_x86_64.tar.gz"
    sha256 "24f78e46db4582f142f72dbc9447ad8249ab595d90dc85421cdb7cce31709380"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Nivl/voorhees/releases/download/v0.9.0/voorhees_0.9.0_Linux_x86_64.tar.gz"
    sha256 "9b0654dd957ee9f5a12de49e10877fee0b9eefe87599c0aa9353895c4cb83316"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Nivl/voorhees/releases/download/v0.9.0/voorhees_0.9.0_Linux_arm64.tar.gz"
    sha256 "b902bf93411a6ec79fbfdb7a7fc6ae8804be9d6533e64ed533aea74620df0ddf"
  end

  def install
    bin.install "voorhees"
  end

  test do
    system "#{bin}/voorhees --version"
  end
end
